[build]
  publish = "."  # publish from root directory since there's no build step
  command = ""   # no build command needed for static sites

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom domain configuration
[context.production]
  environment = { URL = "rishka.site" } 